/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package airport_challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PlaneTest {
    @Test void canCreateAPlane() {
        Plane classUnderTest = new Plane("boeing 247");
        assertEquals(classUnderTest.getPlaneName(), "boeing 247");
    }
    
}
